server_names = ['onion-doh','tor-doh']
listen_addresses = ['0.0.0.0:53']
max_clients = 250
user_name = 'nobody'
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = true
odoh_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true
disabled_server_names = []


force_tcp = false
http3 = false
http3_probe = false

timeout = 10000
keepalive = 30
blocked_query_response = 'refused'

lb_strategy = 'p1'
lb_estimator = true
enable_hot_reload = false

log_level = 3
log_file = '/dev/stdout'
log_file_latest = true
use_syslog = true
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

cert_refresh_concurrency = 10
cert_refresh_delay = 240
cert_ignore_timestamp = false
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
bootstrap_resolvers = []

ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = ''
offline_mode = false

block_ipv6 = true 
block_unqualified = true
block_undelegated = true
reject_ttl = 10

cache = false

[query_log]
file = '/dev/null'
format = 'tsv'
ignored_qtypes = ['DNSKEY', 'NS']


[nx_log]
file = '/dev/stdout'
format = 'tsv'


[monitoring_ui]

enabled = true 
listen_address = "127.0.0.1:8080"

username = "admin"
password = "changeme"

tls_certificate = ""
tls_key = ""

enable_query_log = false 
privacy_level = 2 
max_query_log_entries = 100
max_memory_mb = 1
prometheus_enabled = true 
prometheus_path = "/metrics"


[static]

[static.onion-doh]
   #127.0.0.1
   #one.one.one.one
   #/dns-query
   stamp = 'sdns://AgcAAAAAAAAACTEyNy4wLjAuMQAPb25lLm9uZS5vbmUub25lCi9kbnMtcXVlcnk'         
[static.tor-doh]
   #127.0.0.2
   #one.one.one.one
   #/dns-query
   stamp = 'sdns://AgcAAAAAAAAACTEyNy4wLjAuMgAPb25lLm9uZS5vbmUub25lCi9kbnMtcXVlcnk'
