version: '3.8'
services:

  tor-dns-proxy:
    build: .
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'dig @127.0.0.1 -p 53 cloudflare.com A +short > /dev/null']
      interval: 15s
      timeout: 5s
      retries: 10
    expose:                    #this provides access from within docker only, see the ports section for more information
      - "53/udp"
      #- "9100"                 #optional, if you want metrics for the .onion proxy
      #- "9200"                 #optional, if you want metrics for the clearnet proxy
    #ports:                    #uncomment this option to enable access from your local machine, and comment out the matching entry under "expose"
    #  - "53:53/udp"
    networks:
      - dns_net
    cap_add:
      - NET_ADMIN

networks:
  dns_net
